sudo: required

language: node_js

node_js:
  - "4"
  - "6"

services:
  - docker
  
env:  
  global:
    - DOCKER_VERSION=1.11.2-0~xenial

before_install:
  - sudo apt-get update
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_VERSION}

script:
  - npm run lint
  - npm test
  - npm run test:coverage
  - npm run compile
