sudo: required

language: node_js

node_js:
  - "4"
  - "6"

services:
  - docker
  
env:
  DOCKER_ENGINE_VERSION: "1.9.0"
  
before_script:
  - sudo apt-get update
  - sudo apt-get install -y -q docker-engine=$DOCKER_ENGINE_VERSION

script:
  - npm run lint
  - npm test
  - npm run test:coverage
  - npm run compile
